version: '3.1'

volumes:
  postgres-lawyers-data:

services:
  lawyer-db:
    container_name: lawyer-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lawyer-user
      POSTGRES_PASSWORD: lawyer-password
      POSTGRES_DB: lawyers
    volumes:
      - postgres-lawyers-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U lawyer-user -d lawyers
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - lawyer-net
networks:
  lawyer-net:
