apiVersion: v1
kind: ConfigMap
metadata:
  name: lawyer-api-config

data:
  GO_LISTEN_ADDRESS: ":3001"
  IS_LOCAL: "false"
  OTLP_ENDPOINT: "otel-lawyer-api-collector:4318"
  TZ: "America/Sao_Paulo"
  INGRESS_READY: "true"
  DB_HOST: ""
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: ""
  DB_NAME: "postgres"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lawyer-api
  labels:
    app: lawyer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lawyer-api
  template:
    metadata:
      labels:
        app: lawyer-api
    spec:
      containers:
        - name: lawyer-api
          image: docker.io/mariovalente/lawyers-api:v0.4
          ports:
          - containerPort: 3001
          envFrom:
          - configMapRef:
             name: lawyer-api-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lawyer-api
  labels:
    app: lawyer-api
    self-monitor: "true"
spec:
  selector:
    app: lawyer-api
  ports:
    - name: http
      port: 80
      targetPort: 3001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lawyer-api

  labels:
    app: lawyer-api
spec:
  rules:
    - host: lawyer-api.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: lawyer-api
                port:
                  number: 80
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-lawyer-api
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint:
          http:
            endpoint:

    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      otlp:
        endpoint: "tempo:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lawyer-api
spec:
  selector:
    matchLabels:
      app: lawyer-api
      self-monitor: "true"
  endpoints:
  - path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus

  labels:
    app: prometheus
spec:
  rules:
    - host: prometheus-server.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: prometheus-operator-kube-p-prometheus
                port:
                  number: 9090
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lawyer-api
  labels:
    release: prometheus
spec:
  jobName: lawyer-api
  module: http_2xx
  prober: 
    url: lawyer-api:80
    scheme: http
    path: /health
  targets:
    staticConfig: 
      static: 
       - lawyer-api/health
