name: pre-commit

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: actions/setup-python@v3
        uses: actions/setup-python@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.6
        id: go
      - name: Install go dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/go-critic/go-critic/cmd/gocritic@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
